version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"

    default_reviewers:
      - "niklas-lovgren-beleco"
    default_assignees:
      - "niklas-lovgren-beleco"
    default_labels:
      - "dependencies"
